export const SWITCH_PROFILE_NAVIGATION_ITEM = 'SWITCH_PROFILE_NAVIGATION_ITEM';
export const SWITCH_HEADER_ITEM = 'SWITCH_HEADER_ITEM';
export const SET_NAVIGATION_INITIAL_STATE = 'SET_NAVIGATION_INITIAL_STATE';